spring.application.name=collective-coffee-marketplace

spring.config.import=optional:file:.env[.properties]

spring.profiles.active=${PROFILE}

server.forward-headers-strategy=framework

# PostgreSQL
spring.datasource.username=${PG_USERNAME}
spring.datasource.password=${PG_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Swagger
springdoc.swagger-ui.operationsSorter=method
springdoc.api-docs.path=/documentation
springdoc.api-docs.groups.enabled=true
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.path=/doc/api.html